uint8 TEAM_BLUE=0  # blue, cyan
uint8 TEAM_RED=1  # red, magenta, pink
uint8 TEAM_YELLOW=2  # yellow
uint8 TEAM_BLACK=3  # black, dark gray
uint8 TEAM_WHITE=4  # white
uint8 TEAM_GREEN=5  # green
uint8 TEAM_ORANGE=6  # orange
uint8 TEAM_PURPLE=7  # purple, violet
uint8 TEAM_BROWN=8  # brown
uint8 TEAM_GRAY=9  # lighter gray

uint8 team_number
uint8 team_colour
uint8 score
uint8 penalty_shot
uint16 single_shots
uint16 message_budget
rcgcd_spl_14/RobotInfo[7] players
